name: Performance Benchmark
on: [push]
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    env:
      SAMPLE_DIRNAME: /usr
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install benchmark dependencies
        run: | 
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.17.0/hyperfine_1.17.0_amd64.deb
          sudo dpkg -i hyperfine_1.17.0_amd64.deb
          wget https://github.com/sharkdp/fd/releases/download/v8.7.0/fd_8.7.0_amd64.deb
          sudo dpkg -i fd_8.7.0_amd64.deb

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Run benchmark
        run: |
          hyperfine --warmup=1 --runs=20  --export-markdown=result.md \
            'fd . $SAMPLE_DIRNAME -HI' \
            'node benchmarks/readdir-async-queue.cjs . $SAMPLE_DIRNAME' \
            'node benchmarks/readdir-reccursive.cjs . $SAMPLE_DIRNAME' \
            'node benchmarks/readdir-stats.cjs . $SAMPLE_DIRNAME' \
            'node benchmarks/readdir-types-parallel-callback.cjs . $SAMPLE_DIRNAME' \
            'node benchmarks/readdir-types-parallel-promise.cjs . $SAMPLE_DIRNAME' \
            'node benchmarks/readdir-types.cjs . $SAMPLE_DIRNAME'

      - name: Add job summary
        run: |
          echo '## Results :rocket:' >> $GITHUB_STEP_SUMMARY
          cat result.md >> $GITHUB_STEP_SUMMARY
          echo '------------------' >> $GITHUB_STEP_SUMMARY
          echo '### CPU info' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          lscpu >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '### Memory info' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          free -m >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY