name: Performance Benchmark
on: [push]
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install benchmark dependencies
        run: | 
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.17.0/hyperfine_1.17.0_amd64.deb
          sudo dpkg -i hyperfine_1.17.0_amd64.deb
          wget https://github.com/sharkdp/fd/releases/download/v8.7.0/fd_8.7.0_amd64.deb
          sudo dpkg -i fd_8.7.0_amd64.deb

      - name: Clone benchmarks repository
        working-directory: {{$env.RUNNER_TEMP}}
        run: git clone git@github.com:web-platform-tests/wpt.git

      - run: fd . $RUNNER_TEMP/wpt | wc -l

      # - name: Run benchmark
      #   run: |
      #     hyperfine --export-markdown=result.md \
      #       'node benchmarks/readdir-async-queue.cjs .' \
      #       'node benchmarks/readdir-reccursive.cjs .' \
      #       'node benchmarks/readdir-stats.cjs .' \
      #       'node benchmarks/readdir-types-parallel-callback.cjs .' \
      #       'node benchmarks/readdir-types-parallel-promise.cjs .' \
      #       'node benchmarks/readdir-types.cjs .'

      # - name: Add job summary
      #   run: |
      #     echo '## Results :rocket:' >> $GITHUB_STEP_SUMMARY
      #     cat result.md >> $GITHUB_STEP_SUMMARY
      #     echo '------------------' >> $GITHUB_STEP_SUMMARY
      #     echo '### CPU info' >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      #     lscpu >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      #     echo '### Memory info' >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY
      #     free -m >> $GITHUB_STEP_SUMMARY
      #     echo '```' >> $GITHUB_STEP_SUMMARY